# Generated by Django 3.0.8 on 2021-03-27 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=60, verbose_name='Prato')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('pictureFood', models.ImageField(default='default/default1.png', upload_to='foods/', verbose_name='Imagem')),
                ('description', models.TextField(max_length=120, verbose_name='Descrição')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
