# Generated by Django 3.0.8 on 2021-03-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
